### ISSUE TITLE
Confusing Client API.

### ISSUE THREAD

**Issue by wokalski** [anmonteiro/piaf#16]
This is a fantastic library. The `Oneshot` API is great but the Client API is kinda strange. It's not obvious that the base Uri passed to the Client is transformed (that the params and query are cut off). If you allow arbitrary base Uri then we have another set of problems. For instance how to pass only the query parameters as target. Manual string concatenation seems a bit awful in this scenario.

**Comment by anmonteiro** [comment]
I'd love to understand your issue a little better. I'm gonna try to explain the intended usage of the stateful client API and then reiterate what I think is the issue you're having. Please let me know your thoughts.

So the stateful API is meant to be used as follows:

1. You create a connection with `Piaf.Client.create` and pass it a `Uri.t` that represents the remote address we're gonna connect to.
2. For each of the request functions in the `Client` module, you pass a string with the path / query that you'd like to request, e.g. `Client.get client "/foo?bar=baz"`

So as far as I understand it, your issue seems to be that the `Uri.t` could contain a path / query that we ignore?

**Comment by wokalski** [comment]
Thanks for the explanation, we are on the same page.

> So as far as I understand it, your issue seems to be that the Uri.t could contain a path / query that we ignore?

Precisely.

**Comment by anmonteiro** [comment]
Gotcha -- how do you propose we make that explicit?

**Comment by wokalski** [comment]
To be honest - no idea. Unless you want an Uri builder shipped with Piaf I'm having a hard time coming up with anything.

**Comment by osener** [comment]
Curl, when used with PIPELINE + MULTIPLEX, takes care of establishing & reusing connections by itself: https://curl.haxx.se/libcurl/c/CURLMOPT_PIPELINING.html. What do you think about having something like this? This way, stateful bits would (optionally?) happen under the hood and you'd call Client.get with a `Uri.t`.

**Comment by anmonteiro** [comment]
Piaf also takes care of establishing and reusing connections by itself. A `Client.t`, however, is a connection to a single endpoint. It doesn't (perhaps, yet) make sense to me to allow `Uri.t` in the request functions. I might revisit this assumption in the future.

I'll make this clear in the documentation.

**Comment by anmonteiro** [comment]
I improved the documentation for `Client.create` a little bit in #20. There are currently no plans to change the API itself but I might revisit in the future.
